name: App

on:
  push:
    branches: [ main ] 
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  Make:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run make
