name: App

on:
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  # Run ESLint for the commit
  ESLint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependancies
      run: npm ci
    - name: Run ESLint
      run: npm run lint

  # Build the application and upload the artifacts
  Make:
    needs: [ ESLint ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        node-version: [ 14.x ]

    steps:
      # Checkout Repo
    - name: Checkout Repository
      uses: actions/checkout@v2

      # Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node-version }}

      # Install Dependancies
    - name: Install Dependancies
      run: npm ci

      # Build The Application
    - name: Build Application
      run: npm run make

      # Fetch the package.json version
    - name: Get Package Version
      id: package-version
      uses: tyankatsu0105/read-package-version-actions@v1

      # Upload Build Artifact 
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v1
      with:
        name: YouDownloader-${{ steps.package-version.outputs.version }}-win.zip
        path: ${{ github.workspace }}/out/make/zip/win32/x64/youdownloader-win32-x64-${{ steps.package-version.outputs.version }}.zip

  Post-Comment:
    needs: [ Make ] 
    runs-on: ubuntu-latest

    steps:
    - uses: mshick/add-pr-comment@v1
      with:
        message: The compiled app artifact for this pull request can be found under the "App" workflow once it has been ran successfully.
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' 
        allow-repeats: false
  