name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  # Run ESLint for the commit
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.3.4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependancies
      run: npm ci
    - name: Run ESLint
      run: npm run lint

  # Build the application and upload the artifacts
  Build:
    needs: [ Lint ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        node-version: [ 14.x ]

    steps:
      # Checkout Repo
    - name: Checkout Repository
      uses: actions/checkout@v2.3.4

      # Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node-version }}

      # Install Dependancies
    - name: Install Dependancies
      run: npm ci

      # Build The Application
    - name: Build Application
      run: npm run make