name: "Tagged"

on:
  push:
    tags:
      - "v*"

jobs:

  Make:
    needs: ESLint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        node-version: [ 14.x ]

  Release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependancies
      run: npm ci

    - name: Build Application
      run: npm run make

    - name: Get Package Version
      id: package-version

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: Version ${{ steps.package-version.outputs.version }}
        prerelease: false
        files: |
          ${{ github.workspace }}/out/make/zip/win32/x64/youdownloader-win32-x64-${{ steps.package-version.outputs.version }}.zip