name: Stale

on:
 workflow_dispatch:
 schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3.0.18
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This has been marked stale due to a lack of activity. It will automatically closed in 20 days unless it gets activity.'
        stale-pr-message: 'This has been marked stale due to a lack of activity. It will automatically closed in 30 days unless it gets activity.'
        close-issue-message: 'This issue has been closed due to a lack of acivity after being marked stale.'
        close-pr-message: 'This pull request has been automatically closed as it was marked as stale and remained inactive.'
        exempt-issue-labels: 'in-progress, no-stale'
        exempt-pr-labels: 'in-progress, no-stale'
        exempt-milestones: true
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        close-issue-label: 'stale-closed'
        close-pr-label: 'stale-closed'
        days-before-stale: 60
        days-before-close: 20
