name: Artifact

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  Tidy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '14 day'
        skip-tags: true
        skip-recent: 3
